<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link type="text/css" href="<?php echo Conectar::ruta(); ?>script/css/estilos.css" rel="stylesheet" />
        <script language="javascript" type="text/javascript" src="<?php echo Conectar::ruta();?>script/js/funciones.js"></script>
        
    </head>
    <body>
        <?php echo "Hola Mundo desde el modelo MVC.php";   ?>

        <hr />
        
        <?php require_once("menu.phtml"); ?>
    </body>
</html>