<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link type="text/css" href="<?php echo Conectar::ruta(); ?>script/css/estilos.css" rel="stylesheet" />
        <script language="javascript" type="text/javascript" src="<?php echo Conectar::ruta();?>script/js/funciones.js"></script>

                <title>Producto - <?php echo $datos[0]["producto"];?></title>
        
    </head>
    <body>

        
        <?php require_once("menu.phtml"); ?>
        
        <hr />
        Ver Productos

        <?php
            echo "<pre>"; print_r($datos);
        ?>
        
        
    </body>
</html>